### ISSUE TITLE
onion.gp & onion.lt and others: Web Radio stream not delivered

### ISSUE THREAD

**Issue by freeemint** [starius/onion2web#6]
Can not listen to web-radios from 76qugh5bey5gum7l.onion in particular 76qugh5bey5gum7l.onion/BaroqueRadio . I suspect the server tries to download the stream fully before start sending it to me, which is a pointless/dangerous/stupid behavior with a never ending web-radio-stream. May exploitable for DOS.

**Comment by starius** [comment]
I do not maintain onion.lt.
I'll see what can be done to fix this for onion.gq.

**Comment by freeemint** [comment]
Any news? I know it is not your top priority, have fun fixing that.
Also does my hypothesis makes sense?
If i can help you somehow just say so.

**Comment by starius** [comment]
I don't think this is a vulnerability and DOS, because nginx has some timeout for subrequests.

But I agree with you that it is stupid to load whole page before sending it to a client. Proxy can be redone properly: send a part of data to a client right after it is available on the server. There are problems to be solved. `onion2web` replaces onion domains with onion.gq domains to easy surfing. This replacing 1) is hard to be done on data pieces and 2) it changes document length, that is why `Content-length` header is to be changed. But `Content-length` is sent to client before other data. So the proxy has to download whole page, replace domains and calculate new content length before it can send a header to a client. A related problem: to replace domains, a page is to be decompressed (if it is compressed). It is hard to implement when data is streamed.

I have an idea how to solve content-length problem. It can be unchanged, if pattern length is equal with replacement length. We can generate shorter domains by using another alphabet or by choosing random domains and storing a map from random names to real names. However I don't know how exactly to do the former and I don't like the latter.

There is also a workaround: disable domain replacing feature and enable streaming for non-html content (e.g., for radio or other binary data).

**Comment by freeemint** [comment]
When do you intend to implement this feature?

**Comment by starius** [comment]
I'm trying to implement it for non-html requests. I have no idea about how much time it takes.

The command for testing:

```
$ curl -H 'Cookie: onion2web_confirmed=true' http://76qugh5bey5gum7l.onion.gq/BaroqueRadio > /dev/null
```

Currently it gets no data. If the proxy worked correctly, it would download some bytes.

By the way, I failed to listen to the radio. `torsocks mplayer http://76qugh5bey5gum7l.onion/BaroqueRadio` is failing with `Couldn't resolve name for AF_INET: 76qugh5bey5gum7l.onion`.

**Comment by freeemint** [comment]
It works!

**Comment by starius** [comment]
I haven't done it yet.

The problem with mplayer was solved by upgrading torsocks from 1.x to 2.x. See also https://trac.torproject.org/projects/tor/ticket/11205

**Comment by starius** [comment]
It works for me in Firefox Browser: http://76qugh5bey5gum7l.onion.gq/BaroqueRadio.m3u

To use it with mplayer, cookie file is needed to pass onion2web_confirmed=true. I have tested it locally with confirmations disabled and it worked.

**Comment by starius** [comment]
I managed to use it with mplayer:

```
$ echo -e '.onion.gq\tTRUE\t/\tFALSE\t2000000000\tonion2web_confirmed\ttrue' > cookies
$ mplayer -cookies -cookies-file cookies http://76qugh5bey5gum7l.onion.gq/BaroqueRadio
```

**Comment by freeemint** [comment]
Thank you i can listen to my favorite music again. Do you intend to push your changes to other onion access points?

**Comment by starius** [comment]
I manage only onion.gq. Please ask admins of other gates to do similar changes.
